# Generated by Django 6.0.7 on 2026-08-15 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0010_contabancariafuncionario_digito_agencia_and_more'),
        ('usuarios', '0003_perfilusuario_setor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('finalidade', models.CharField(max_length=200, verbose_name='Finalidade da viagem')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('solicitado', 'Solicitado'), ('prestado', 'Prestado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.contabancariafuncionario', verbose_name='Conta Bancária')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.funcionario', verbose_name='Motorista')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.setor', verbose_name='Setor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
