# Generated by Django 6.0.7 on 2026-08-15 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_contabancariafuncionario_digito_agencia_and_more'),
        ('financeiro', '0001_initial'),
        ('usuarios', '0003_perfilusuario_setor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiantamento',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adiantamentos', to='cadastros.contabancariafuncionario', verbose_name='Conta Bancária'),
        ),
        migrations.AlterField(
            model_name='adiantamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adiantamentos', to='cadastros.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='adiantamento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adiantamentos', to='cadastros.funcionario', verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='adiantamento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adiantamentos', to='usuarios.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='adiantamento',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adiantamentos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
