# Generated by Django 6.0.7 on 2026-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_adiantamento_conta_bancaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiantamento',
            name='finalidade',
            field=models.CharField(choices=[('despesas_viagem', 'Despesas com viagens'), ('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('pedagio', 'Pedágio'), ('abastecimento', 'Abastecimento'), ('emergencia', 'Emergência'), ('outros', 'Outros')], default='despesas_viagem', max_length=30, verbose_name='Finalidade'),
        ),
    ]
