# Generated by Django 6.0.7 on 2026-08-21 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_contabancariafuncionario_digito_agencia_and_more'),
        ('financeiro', '0003_alter_adiantamento_finalidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteAdiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Emissão')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Lote de Adiantamento',
                'verbose_name_plural': 'Lotes de Adiantamentos',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adiantamentos', to='financeiro.loteadiantamento', verbose_name='Lote'),
        ),
    ]
