# Generated by Django 6.0.7 on 2026-08-23 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_loteadiantamento_adiantamento_lote'),
        ('usuarios', '0003_perfilusuario_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteadiantamento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.setor', verbose_name='Setor'),
        ),
    ]
