# Generated by Django 6.0.7 on 2026-08-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_loteadiantamento_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='adiantamento',
            name='historico_agencia',
            field=models.CharField(blank=True, max_length=20, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_banco',
            field=models.CharField(blank=True, max_length=3, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_chave_pix',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_cpf_motorista',
            field=models.CharField(blank=True, max_length=20, verbose_name='CPF do Motorista'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_digito_agencia',
            field=models.CharField(blank=True, max_length=2, verbose_name='Dígito da Agência'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_digito_conta',
            field=models.CharField(blank=True, max_length=2, verbose_name='Dígito da Conta'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_nome_motorista',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Motorista'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_numero_conta',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número da Conta'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_tipo_chave_pix',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Chave PIX'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_tipo_conta',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='adiantamento',
            name='historico_titular',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titular da Conta'),
        ),
    ]
