# Generated by Django 6.0.7 on 2026-08-30 17:38

from django.db import migrations


def preencher_historico_adiantamentos(apps, schema_editor):
    Adiantamento = apps.get_model(
        "financeiro",
        "Adiantamento",
    )

    adiantamentos = Adiantamento.objects.select_related(
        "funcionario",
        "conta_bancaria",
    ).all()

    for adiantamento in adiantamentos:
        funcionario = adiantamento.funcionario
        conta = adiantamento.conta_bancaria

        # Banco
        banco = conta.banco or ""

        # Tipo da conta
        tipos_conta = dict(conta._meta.get_field("tipo_conta").choices)

        tipo_conta = tipos_conta.get(
            conta.tipo_conta,
            conta.tipo_conta or "",
        )

        # Tipo da chave PIX
        tipos_pix = dict(conta._meta.get_field("tipo_chave_pix").choices)

        tipo_chave_pix = tipos_pix.get(
            conta.tipo_chave_pix,
            conta.tipo_chave_pix or "",
        )

        adiantamento.historico_nome_motorista = funcionario.nome or ""

        adiantamento.historico_cpf_motorista = getattr(funcionario, "cpf", "") or ""

        adiantamento.historico_titular = conta.titular or ""

        adiantamento.historico_banco = banco

        adiantamento.historico_agencia = conta.agencia or ""

        adiantamento.historico_digito_agencia = conta.digito_agencia or ""

        adiantamento.historico_numero_conta = conta.numero_conta or ""

        adiantamento.historico_digito_conta = conta.digito_conta or ""

        adiantamento.historico_tipo_conta = tipo_conta

        adiantamento.historico_tipo_chave_pix = tipo_chave_pix

        adiantamento.historico_chave_pix = conta.chave_pix or ""

        Adiantamento.objects.filter(
            pk=adiantamento.pk,
        ).update(
            historico_nome_motorista=(adiantamento.historico_nome_motorista),
            historico_cpf_motorista=(adiantamento.historico_cpf_motorista),
            historico_titular=(adiantamento.historico_titular),
            historico_banco=(adiantamento.historico_banco),
            historico_agencia=(adiantamento.historico_agencia),
            historico_digito_agencia=(adiantamento.historico_digito_agencia),
            historico_numero_conta=(adiantamento.historico_numero_conta),
            historico_digito_conta=(adiantamento.historico_digito_conta),
            historico_tipo_conta=(adiantamento.historico_tipo_conta),
            historico_tipo_chave_pix=(adiantamento.historico_tipo_chave_pix),
            historico_chave_pix=(adiantamento.historico_chave_pix),
        )


def reverter_historico_adiantamentos(apps, schema_editor):
    Adiantamento = apps.get_model(
        "financeiro",
        "Adiantamento",
    )

    Adiantamento.objects.all().update(
        historico_nome_motorista="",
        historico_cpf_motorista="",
        historico_titular="",
        historico_banco="",
        historico_agencia="",
        historico_digito_agencia="",
        historico_numero_conta="",
        historico_digito_conta="",
        historico_tipo_conta="",
        historico_tipo_chave_pix="",
        historico_chave_pix="",
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "financeiro",
            "0006_adiantamento_historico_agencia_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            preencher_historico_adiantamentos,
            reverter_historico_adiantamentos,
        ),
    ]
