# Generated by Django 6.0.7 on 2026-08-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_preencher_historico_adiantamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adiantamento',
            name='historico_banco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
    ]
