# Generated by Django 6.0.7 on 2026-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_alter_adiantamento_historico_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteadiantamento',
            name='responsavel_historico',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='loteadiantamento',
            name='setor_historico',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
