# Generated by Django 6.0.7 on 2026-09-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_loteadiantamento_responsavel_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteadiantamento',
            name='emitido_por_historico',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
