from django.urls import path

from .views import (
    alterar_senha,
    meu_perfil,
    meu_perfil_update,
    redefinir_senha,
    setor_create,
    setor_delete,
    setor_list,
    setor_update,
    usuario_create,
    usuario_list,
    usuario_toggle_status,
    usuario_update,
)

app_name = "usuarios"

urlpatterns = [
    path(
        "novo/",
        usuario_create,
        name="usuario_create",
    ),
    path(
        "perfil/",
        meu_perfil,
        name="meu_perfil",
    ),
    path(
        "perfil/editar/",
        meu_perfil_update,
        name="meu_perfil_update",
    ),
    path(
        "",
        usuario_list,
        name="usuario_list",
    ),
    path(
        "<int:pk>/editar/",
        usuario_update,
        name="usuario_update",
    ),
    path(
        "alterar-senha/",
        alterar_senha,
        name="alterar_senha",
    ),
    path(
        "<int:pk>/redefinir-senha/",
        redefinir_senha,
        name="redefinir_senha",
    ),
    path(
        "<int:pk>/status/",
        usuario_toggle_status,
        name="usuario_toggle_status",
    ),
    path(
        "setores/",
        setor_list,
        name="setor_list",
    ),
    path(
        "setores/novo/",
        setor_create,
        name="setor_create",
    ),
    path(
        "setores/<int:pk>/editar/",
        setor_update,
        name="setor_update",
    ),
    path(
        "setores/<int:pk>/excluir/",
        setor_delete,
        name="setor_delete",
    ),
]
