# Generated by Django 6.0.7 on 2026-08-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(choices=[('OP', 'Operador'), ('GE', 'Gestor'), ('AD', 'Administrador')], default='OP', max_length=2, verbose_name='Perfil'),
        ),
    ]
