# Generated by Django 6.0.7 on 2026-08-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.setor', verbose_name='Setor'),
        ),
    ]
