# Generated by Django 6.0.7 on 2026-08-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('possui_placa', models.BooleanField(default=True, verbose_name='Possui placa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Classe Operacional',
                'verbose_name_plural': 'Classes Operacionais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancariaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('numero_conta', models.CharField(max_length=30, verbose_name='Número da conta')),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Conta corrente'), ('poupanca', 'Conta poupança')], default='corrente', max_length=10, verbose_name='Tipo de conta')),
                ('tipo_chave_pix', models.CharField(choices=[('cpf', 'CPF'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('aleatoria', 'Chave aleatória')], default='cpf', max_length=10, verbose_name='Tipo de chave PIX')),
                ('chave_pix', models.CharField(max_length=150, verbose_name='Chave PIX')),
                ('padrao', models.BooleanField(default=True, verbose_name='Conta padrão')),
            ],
            options={
                'verbose_name': 'Conta bancária de funcionário',
                'verbose_name_plural': 'Contas bancárias de funcionários',
                'ordering': ['funcionario__nome', '-padrao', 'banco'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('razao_social', models.CharField(max_length=150, unique=True, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='StatusEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('permite_utilizacao', models.BooleanField(default=True, verbose_name='Permite utilização')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Status do Equipamento',
                'verbose_name_plural': 'Status dos Equipamentos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('frota', models.CharField(max_length=20, unique=True, verbose_name='Frota')),
                ('placa', models.CharField(blank=True, max_length=10, verbose_name='Placa')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('marca', models.CharField(blank=True, max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=60, verbose_name='Modelo')),
                ('ano_fabricacao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano Fabricação')),
                ('ano_modelo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano Modelo')),
                ('renavam', models.CharField(blank=True, max_length=20, verbose_name='Renavam')),
                ('chassi', models.CharField(blank=True, max_length=30, verbose_name='Chassi')),
                ('cor', models.CharField(blank=True, max_length=30, verbose_name='Cor')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('classe_operacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.classeoperacional', verbose_name='Classe Operacional')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ('frota',),
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('numero_cnh', models.CharField(blank=True, max_length=30, verbose_name='Número da CNH')),
                ('validade_cnh', models.DateField(blank=True, null=True, verbose_name='Validade da CNH')),
                ('cursos', models.TextField(blank=True, verbose_name='Cursos')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.funcao', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
