# Generated by Django 6.0.7 on 2026-07-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('numero_cnh', models.CharField(blank=True, max_length=30, verbose_name='Número da CNH')),
                ('validade_cnh', models.DateField(blank=True, null=True, verbose_name='Validade da CNH')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('cursos', models.TextField(blank=True, verbose_name='Cursos')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
