# Generated by Django 6.0.7 on 2026-08-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='usuarios.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='contabancariafuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_bancarias', to='cadastros.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.statusequipamento', verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='contabancariafuncionario',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('funcionario',), name='uma_conta_padrao_por_funcionario'),
        ),
    ]
