# Generated by Django 6.0.7 on 2026-08-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('possui_placa', models.BooleanField(default=True, verbose_name='Possui placa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Classe Operacional',
                'verbose_name_plural': 'Classes Operacionais',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
