# Generated by Django 6.0.7 on 2026-08-09 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='setor',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.empresa', verbose_name='Empresa'),
        ),
    ]
