# Generated by Django 6.0.7 on 2026-08-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_classeoperacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancariaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('numero_conta', models.CharField(max_length=30, verbose_name='Número da conta')),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Conta corrente'), ('poupanca', 'Conta poupança')], default='corrente', max_length=10, verbose_name='Tipo de conta')),
                ('tipo_chave_pix', models.CharField(choices=[('cpf', 'CPF'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('aleatoria', 'Chave aleatória')], default='cpf', max_length=10, verbose_name='Tipo de chave PIX')),
                ('chave_pix', models.CharField(max_length=150, verbose_name='Chave PIX')),
                ('padrao', models.BooleanField(default=True, verbose_name='Conta padrão')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_bancarias', to='cadastros.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Conta bancária de funcionário',
                'verbose_name_plural': 'Contas bancárias de funcionários',
                'ordering': ['funcionario__nome', '-padrao', 'banco'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('funcionario',), name='uma_conta_padrao_por_funcionario')],
            },
        ),
    ]
