# Generated by Django 6.0.7 on 2026-08-01 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_statusequipamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('frota', models.CharField(max_length=20, unique=True, verbose_name='Frota')),
                ('placa', models.CharField(blank=True, max_length=10, verbose_name='Placa')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('marca', models.CharField(blank=True, max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=60, verbose_name='Modelo')),
                ('ano_fabricacao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano Fabricação')),
                ('ano_modelo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano Modelo')),
                ('renavam', models.CharField(blank=True, max_length=20, verbose_name='Renavam')),
                ('chassi', models.CharField(blank=True, max_length=30, verbose_name='Chassi')),
                ('cor', models.CharField(blank=True, max_length=30, verbose_name='Cor')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('classe_operacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.classeoperacional', verbose_name='Classe Operacional')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.empresa', verbose_name='Empresa')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.statusequipamento', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ('frota',),
            },
        ),
    ]
