# Generated by Django 6.0.7 on 2026-08-10 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_funcionario_funcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='status',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.statusequipamento', verbose_name='Status operacional'),
        ),
    ]
