# Generated by Django 6.0.7 on 2026-08-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_remove_equipamento_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status_operacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.statusequipamento', verbose_name='Status operacional'),
        ),
    ]
