# Generated by Django 6.0.7 on 2026-08-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_equipamento_status_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancariafuncionario',
            name='digito_agencia',
            field=models.CharField(blank=True, max_length=2, verbose_name='Dígito da agência'),
        ),
        migrations.AddField(
            model_name='contabancariafuncionario',
            name='digito_conta',
            field=models.CharField(blank=True, max_length=2, verbose_name='Dígito da conta'),
        ),
        migrations.AddField(
            model_name='contabancariafuncionario',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='contabancariafuncionario',
            name='titular',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titular da conta'),
        ),
        migrations.AlterField(
            model_name='contabancariafuncionario',
            name='banco',
            field=models.CharField(choices=[('001', '001 - Banco do Brasil'), ('104', '104 - Caixa Econômica Federal'), ('237', '237 - Bradesco'), ('341', '341 - Itaú'), ('033', '033 - Santander'), ('748', '748 - Sicredi'), ('756', '756 - Sicoob'), ('077', '077 - Banco Inter'), ('260', '260 - Nubank'), ('336', '336 - C6 Bank'), ('290', '290 - PagBank'), ('323', '323 - Mercado Pago'), ('212', '212 - Banco Original'), ('208', '208 - BTG Pactual')], max_length=3, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='contabancariafuncionario',
            name='padrao',
            field=models.BooleanField(default=False, verbose_name='Conta padrão'),
        ),
        migrations.AlterField(
            model_name='contabancariafuncionario',
            name='tipo_conta',
            field=models.CharField(choices=[('corrente', 'Conta corrente'), ('poupanca', 'Conta poupança'), ('pagamento', 'Conta de pagamento'), ('digital', 'Conta digital'), ('salario', 'Conta salário')], default='corrente', max_length=10, verbose_name='Tipo de conta'),
        ),
    ]
