# Generated by Django 6.0.7 on 2026-08-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_contabancariafuncionario_digito_agencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo'),
        ),
    ]
